### ISSUE TITLE
Window manager freezes when borderless window is stuck

### ISSUE THREAD

**Issue by kmatheussen** [fvwmorg/fvwm#78] opened 2019-04-30 12:49 UTC
Hi, this is an old bug. I've probably had to reset my computer hundreds of times throughout the years because of this. Usually I'm able to press Ctrl + Alt + F7 to get into a terminal and kill the offending program, but on my laptop I haven't enabled this possibility for security reasons. And then the only option has been to reset the computer.

Steps to reproduce:

1. Copy this text to popupmenu.cpp

```
#include <QApplication>
#include <QMenu>

// g++ `pkg-config --cflags --libs Qt5Gui Qt5Widgets` popupmenu.cpp -fPIC

int main(int argc, char *argv[]){

  QApplication app(argc, argv);
    
  QMenu *menu=new QMenu(NULL);
  
  menu->addAction(QString("Copy"));
  menu->addAction(QString("Cut"));
  menu->addAction(QString("Paste"));
  menu->addAction(QString("Select"));
  menu->addAction(QString("Close"));

  menu->show();

  abort();
  
  return 0;
}
```

2. Compile it like this: ```g++ `pkg-config --cflags --libs Qt5Gui Qt5Widgets` popupmenu.cpp -fPIC```

3. Run gdb with this program: ```gdb a.out```

4. Press r to start the program.

5. The window manager freezes. If you are able to kill the process, you don't have to reset the computer.

If anyone has a workaround to avoid freezing the computer, I would be very happy since this is extremely annoying.

**Comment by ThomasAdam** [comment] 2019-05-01 10:47
Hi,

I can't reproduce this problem at all, I'm afraid.  At the point that `menu->show()` would have run (and gdb has paused). FVWM isn't freezing at all for me.

What you can do to help me though is build FVWM from git (with debugging symbols present still). and attach gdb to FVWM when it freezes for you -- that way, you can get me a backtrace from FVWM and I'll be able to narrow down what's going on.

**Comment by kmatheussen** [comment] 2019-05-01 11:37
Seems like I'm running a kernel where I can't log in to tty. Dist is too old, and I don't want to compile a new kernel. So there's no way to easy way for me to avoid freezing the computer now. I'll try again in a couple of weeks when I have access to another computer.

Strange that you can't reproduce it. This has been 100% reproducable for years, on multiple computers. I also tried without a custom fvwm configuration file, and the same thing happened.

**Comment by kmatheussen** [comment] 2019-05-01 11:37
I've also tried git HEAD of fvwm.

**Comment by kmatheussen** [comment] 2019-05-01 11:43
Maybe the event loop didn't have time to open the menu on your computer. This one might work better:
```
#include <QApplication>
#include <QMenu>

// g++ `pkg-config --cflags --libs Qt5Gui Qt5Widgets` popupmenu.cpp -fPIC

int main(int argc, char *argv[]){

  QApplication app(argc, argv);
    
  QMenu *menu=new QMenu(NULL);
  
  menu->addAction(QString("Copy"));
  menu->addAction(QString("Cut"));
  menu->addAction(QString("Paste"));
  menu->addAction(QString("Select"));
  menu->addAction(QString("Close"));

  menu->show();

  QCoreApplication::processEvents(QEventLoop::AllEvents, 2000);
                                  
  abort();
  
  return 0;
}
```

**Comment by kmatheussen** [comment] 2019-05-01 11:55
Unless the last one doesn't trigger the problem for you, I guess it's a newer version of X or the kernel that has fixed it somehow. I don't update my computers very often.

```
[kjetil@localhost ~]$ Xorg -version

X.Org X Server 1.14.5
Release Date: 2013-12-12
X Protocol Version 11, Revision 0
Build Operating System: intel-appliance-0 3.12-0.bpo.1-amd64 
Current Operating System: Linux localhost.localdomain 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.19.8-100.fc20.x86_64 root=/dev/mapper/luks-ed3998da-34d5-4eec-afab-1f2831ecd0cc ro acpi_osi=Linux rd.lvm.lv=fedora/swap vconsole.font=latarcyrheb-sun16 rd.lvm.lv=fedora/root rd.luks.uuid=luks-ed3998da-34d5-4eec-afab-1f2831ecd0cc rhgb quiet quiet splash acpi_backlight=vendor LANG=en_US.UTF-8
Build Date: 28 April 2014  03:18:56PM
Build ID: xorg-x11-server 1.14.5-20.intel20141 
Current version of pixman: 0.30.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.

[kjetil@localhost ~]$ uname -a
Linux localhost.localdomain 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by ThomasAdam** [comment] 2019-05-01 12:26
Still can't reproduce this, I'm afraid.  I'll close this for now -- and should the problem reoccur, please feel free to reopen.

**Closed by ThomasAdam** 2019-05-01 12:26 UTC

**Comment by kmatheussen** [comment] 2019-05-01 12:36
Yeah, I was about to close it too. It happens in Gnome as well. I guess it's an X bug that has been fixed recently.
